name: Create Release
on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Bun
              uses: oven-sh/setup-bun@v2
              with:
                bun-version: "1.2.14"
            
            - name: Install dependencies
              run: bun install

            - name: Build EXE
              run: bun build ./src/index.ts --compile --sourcemap --target=bun-windows-x64 --outfile companion.exe

            - name: Create zip archive
              run: zip -r ${{ github.event.repository.name }}.zip "100% Checklist.exe" config.json companion.exe

            - name: Create release
              uses: softprops/action-gh-release@v1
              with:
                generate_release_notes: true
                draft: false
                prerelease: false
                tag_name: release-${{ github.sha }}
                release_name: Release ${{ github.sha }}
                files: ./companion.zip
